version: '3'

services:
  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  api:
    container_name: api
    build: .
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["python", "/app/manage.py", "runserver", "0:8000"]
    ports:
      - "8000:8000"

volumes:
  db:
